[package]
name = "aptosx-liquid-token"
version = "0.0.0"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
core_resources = "0xA550C18"
vm_reserved = "0x0"
liquidToken = "_"
